# Base configuration for Job Search Assistant
# This file contains all default values and the complete configuration structure
# Environment-specific files (dev.toml, stage.toml) override these defaults

[general]
name = "job-search-assistant"
tagline = "AI-powered job search assistant who does the heavy lifting and gets the job for you"
version = "0.1.0"
debug = false

[logging]
level = "INFO"
format = "%(asctime)s %(name)s [%(levelname)s] %(message)s"

[llm_profiles.anthropic_extraction]
provider = "anthropic"
model = "claude-3-5-haiku-20241022"
temperature = 0.0
max_tokens = 512

[llm_profiles.google_extraction]
provider = "google"
model = "gemini-2.5-flash"
temperature = 0.0
max_tokens = 512

# Agent task to LLM profile mapping
[agents]
job_evaluation_extraction = "anthropic_extraction"

# Business logic parameters for job evaluation
[evaluation_criteria]
min_salary = 100000
remote_required = true
ic_title_requirements = ["lead", "staff", "principal", "senior staff"]

[observability.langfuse]
enabled = false
host = "https://us.cloud.langfuse.com"
# public_key and secret_key loaded from environment variables
