# Base configuration for Job Search Assistant
# This file contains all default values and the complete configuration structure
# Environment-specific files (dev.toml, stage.toml) override these defaults

[general]
name = "job-search-assistant"
version = "0.1.0"
debug = false

[logging]
level = "INFO"
format = "%(asctime)s %(name)s [%(levelname)s] %(message)s"

[llm_profiles.anthropic_reasoning]
provider = "anthropic"
model = "claude-sonnet-4-20250514"
temperature = 0.0
max_tokens = 1024

# Agent task to LLM profile mapping
[agents]
job_evaluation_extraction = "anthropic_reasoning"
job_evaluation_reasoning = "anthropic_reasoning"

# Business logic parameters for job evaluation
[evaluation_criteria]
min_salary = 160000
remote_required = true
ic_title_requirements = ["lead", "staff", "principal", "senior staff"]

[observability.langfuse]
enabled = false
host = "https://us.cloud.langfuse.com"
# public_key and secret_key loaded from environment variables
