# Test environment overrides
# Only define settings that differ from base.toml

[logging]
level = "WARNING"  # Less noise during tests

# Disable external services during tests
[observability.langfuse]
enabled = false

# Use fastest/cheapest model for tests
[llm_profiles.anthropic_reasoning]
model = "claude-3-5-haiku-20241022"  # Fastest model
temperature = 0.0  # Deterministic for testing
max_tokens = 256   # Minimal tokens for tests
